# Mathematical Foundation Laboratory
## UE25MA242A – Mathematical Foundations for AI & Data Science
### Project: Linear Algebraic Transformations in Euclidean and Non-Euclidean Geometries

This notebook serves as the interactive mathematical proof-of-concept for the project.
It demonstrates how **vectors**, **matrices**, **bilinear/quadratic forms**, and **matrix preservation conditions** define and transform **Euclidean**, **Spherical**, and **Hyperbolic** geometries.


---
## 01. Vectors and Vector Spaces
Vectors in $\mathbb{R}^2$ and $\mathbb{R}^3$ represent geometric points.


In [1]:
import sys
sys.path.append('../src')
import numpy as np
from geometry_linear_algebra import *

v2 = np.array([3.0, 4.0])
v3 = np.array([1.0, 2.0, 2.0])

print("2D Vector v2:", v2)
print("3D Vector v3:", v3)


2D Vector v2: [3. 4.]
3D Vector v3: [1. 2. 2.]


---
## 02. Inner Products and Norms
The Euclidean inner product $\langle u, v \rangle = u^T v$ defines vector lengths (L2 norm) $\|v\| = \sqrt{v^T v}$ and orthogonality.


In [2]:
u = np.array([1.0, 0.0])
v = np.array([0.0, 1.0])

print("Dot product u^T v:", dot_product(u, v))
print("Norm ||v2||:", vector_norm(v2))


Dot product u^T v: 0.0
Norm ||v2||: 5.0


---
## 03. 2D Euclidean Rotation Matrices & Triangle Isometry
The 2D rotation matrix is given by:
$$R(\theta) = \begin{bmatrix} \cos\theta & -\sin\theta \\ \sin\theta & \cos\theta \end{bmatrix}$$
Demonstrating $R^T R = I_2$ and triangle angle sum $\Sigma = 180^\circ$.


In [3]:
theta_deg = 45.0
R = euclidean_rotation_matrix(theta_deg)
R_T_R, max_diff = check_matrix_preservation(R, np.eye(2))

A_e = np.array([0.0, 0.0])
B_e = np.array([1.5, 0.0])
C_e = np.array([0.5, 1.2])

ang_A, ang_B, ang_C, sum_euc = euclidean_triangle_angles(A_e, B_e, C_e)

print("Rotation Matrix R(45 deg):")
print(R)
print("R^T R Deviation from I_2:", max_diff)
print(f"Euclidean Angles: A={ang_A:.1f} deg, B={ang_B:.1f} deg, C={ang_C:.1f} deg")
print(f"Euclidean Angle Sum: {sum_euc:.1f} deg (Always 180 deg)")


Rotation Matrix R(45 deg):
[[ 0.70710678 -0.70710678]
 [ 0.70710678  0.70710678]]
R^T R Deviation from I_2: 1.0146536357569526e-17
Euclidean Angles: A=67.4 deg, B=50.2 deg, C=62.4 deg
Euclidean Angle Sum: 180.0 deg (Always 180 deg)


---
## 04. Spherical Representation ($p \in \mathbb{R}^3, p^T p = 1$) & Spherical Excess
Points on the unit sphere $S^2$ satisfy the constraint $x^2 + y^2 + z^2 = 1$.
Demonstrating that spherical triangle angle sum $\Sigma > 180^\circ$.


In [4]:
A_s = latlon_to_cartesian(45.0, 0.0)
B_s = latlon_to_cartesian(0.0, 60.0)
C_s = latlon_to_cartesian(60.0, 30.0)

ang_As, ang_Bs, ang_Cs, sum_sph, excess_sph = spherical_triangle_angles(A_s, B_s, C_s)

print("Constraint A^T A =", dot_product(A_s, A_s))
print(f"Spherical Angles: A={ang_As:.1f} deg, B={ang_Bs:.1f} deg, C={ang_Cs:.1f} deg")
print(f"Spherical Angle Sum : {sum_sph:.1f} deg (> 180 deg)")
print(f"Spherical Excess E  : +{excess_sph:.1f} deg")


Constraint A^T A = 1.0
Spherical Angles: A=73.0 deg, B=24.8 deg, C=97.1 deg
Spherical Angle Sum : 194.9 deg (> 180 deg)
Spherical Excess E  : +14.9 deg


---
## 05. Hyperboloid Model ($p^T H p = -1$) & Angular Defect
In Minkowski 3-space $\mathbb{R}^{2,1}$, the hyperbolic plane is the upper sheet ($z > 0$) of the hyperboloid:
$$x^2 + y^2 - z^2 = -1 \quad \implies \quad p^T H p = -1, \quad H = \text{diag}(1, 1, -1)$$
Demonstrating that hyperbolic triangle angle sum $\Sigma < 180^\circ$.


In [5]:
A_h = hyperboloid_point_from_disk(-0.4, 0.3)
B_h = hyperboloid_point_from_disk(0.5, -0.2)
C_h = hyperboloid_point_from_disk(0.0, -0.6)

ang_Ah, ang_Bh, ang_Ch, sum_hyp, defect_hyp = hyperbolic_triangle_angles(A_h, B_h, C_h)

print("Minkowski Form A^T H A:", minkowski_product(A_h, A_h))
print(f"Hyperbolic Angles: A={ang_Ah:.1f} deg, B={ang_Bh:.1f} deg, C={ang_Ch:.1f} deg")
print(f"Hyperbolic Angle Sum : {sum_hyp:.1f} deg (< 180 deg)")
print(f"Angular Defect D     : -{defect_hyp:.1f} deg")


Minkowski Form A^T H A: -1.0000000000000004
Hyperbolic Angles: A=22.3 deg, B=45.7 deg, C=45.0 deg
Hyperbolic Angle Sum : 113.0 deg (< 180 deg)
Angular Defect D     : -67.0 deg


---
## 06. Lorentz Boost Transformation ($B^T H B = H$)
Lorentz transformations preserve the Minkowski bilinear form: $B^T H B = H$.


In [6]:
t_rapidity = 0.8
B_lorentz = lorentz_boost_x(t_rapidity)
A_h_trans = matrix_vector_mult(B_lorentz, A_h)

B_T_H_B, diff = check_matrix_preservation(B_lorentz, H_METRIC)

print("Lorentz Boost Matrix B(0.8):")
print(B_lorentz)
print("Preservation check B^T H B = H Max Dev:", diff)
print("Transformed Point A' Minkowski Form:", minkowski_product(A_h_trans, A_h_trans))


Lorentz Boost Matrix B(0.8):
[[1.33743495 0.         0.88810598]
 [0.         1.         0.        ]
 [0.88810598 0.         1.33743495]]
Preservation check B^T H B = H Max Dev: 2.220446049250313e-16
Transformed Point A' Minkowski Form: -1.0000000000000007


---
## 07. Side-by-Side Comparison of Geometries


In [7]:
import pandas as pd

comparison_data = {
    'Geometry Space': ['Euclidean (E^2)', 'Spherical (S^2)', 'Hyperbolic (H^2)'],
    'Curvature K': ['0', '+1', '-1'],
    'Triangle Angle Sum': [f'{sum_euc:.1f} deg (= 180 deg)', f'{sum_sph:.1f} deg (> 180 deg)', f'{sum_hyp:.1f} deg (< 180 deg)'],
    'Geodesic Type': ['Straight Line', 'Great Circle Arc', 'Orthogonal Disk Arc'],
    'Metric Tensor M': ['Identity I_2', 'Identity I_3', 'Minkowski H = diag(1,1,-1)'],
    'Preserving Condition': ['R^T R = I_2', 'R^T R = I_3', 'B^T H B = H']
}

df = pd.DataFrame(comparison_data)
df


,Geometry Space,Curvature K,Triangle Angle Sum,Geodesic Type,Metric Tensor M,Preserving Condition
0,Euclidean (E^2),0,180.0 deg (= 180 deg),Straight Line,Identity I_2,R^T R = I_2
1,Spherical (S^2),+1,194.9 deg (> 180 deg),Great Circle Arc,Identity I_3,R^T R = I_3
2,Hyperbolic (H^2),-1,113.0 deg (< 180 deg),Orthogonal Disk Arc,"Minkowski H = diag(1,1,-1)",B^T H B = H
